version: 0.2.{build}
image: Visual Studio 2017
configuration: Release
skip_tags: true

environment:
  SLN: CommonNetExtensions.sln
  EXTPROJ: CommonNet.Extensions\CommonNet.Extensions.csproj
  TESTPROJ: CommonNet.Extensions.Tests\CommonNet.Extensions.Tests.csproj
  SONAR_TOKEN:
    secure: z4HgF9R+nzhk2AZ7wkgyEdJg+VLdrqOlGp6R2xEiBU5HKXDhcxjemIkXboKkYqn0

init:
  - cmd: dotnet tool install --global dotnet-sonarscanner
  - ps: $Env:LABEL = "release/v" + $Env:APPVEYOR_BUILD_VERSION

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

for:
# Master branch only
-
  branches:
    only:
      - master

  configuration:
    - Release

  before_build:
    - cmd: dotnet restore %SLN%

  build_script:
    - cmd: dotnet build %SLN% -c %CONFIGURATION%

  after_build:
    - cmd: dotnet pack %EXTPROJ% -c %CONFIGURATION% --include-symbols

  test_script:
    - cmd: dotnet test %TESTPROJ% -c %CONFIGURATION%

  artifacts:
    - path: 'CommonNet.Extensions\**\*.nupkg'
      name: CommonNet.Extensions

  nuget:
    disable_publish_on_pr: true

  deploy:
    provider: NuGet
    api_key:
      secure: YGj7yA5GXDyQeEY8SspSVT7RSM1NcOFSUdSsDIYCGvxaFl4h1gOz73vKtfZxsB3d
    skip_symbols: false
    artifact: /.*\.nupkg/

    # TODO: tag repo

# All other branches
-
  before_build:
    - cmd: dotnet restore %SLN%
    - cmd: dotnet sonarscanner begin /k:"dmako_CommonNetExtensions" /d:sonar.organization="dmako-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%SONAR_TOKEN%" /version:"%VERSION%" /d:sonar.cs.opencover.reportsPaths="CommonNet.Extensions.Tests\ccresult.xml"

  build_script:
    - cmd: dotnet build %SLN% -c %CONFIGURATION%

  test_script:
    - cmd: dotnet test -c %CONFIGURATION% /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=.\ccresult.xml %TESTPROJ%

  after_test:
    - cmd: dotnet sonarscanner end /d:sonar.login="%SONAR_TOKEN%"
