<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">net8.0;net9.0;net48</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TargetArchitecture>x64</TargetArchitecture>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition=" '$(OS)' == 'Windows_NT' ">win-x64</RuntimeIdentifier>
    <NoWarn>$(NoWarn);TUnit0046</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.msbuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Condition=" '$(TargetFramework)' == 'net48'" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Condition=" '$(TargetFramework)' == 'net48'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonNet.DependencyInjection\CommonNet.DependencyInjection.csproj" />
    <ProjectReference Include="..\CommonNet.Extensions\CommonNet.Extensions.csproj" />
    <ProjectReference Include="..\CommonNet.Json\CommonNet.Json.csproj" />
    <ProjectReference Include="..\CommonNet.Logging\CommonNet.Logging.csproj" />
  </ItemGroup>

</Project>
